### ISSUE TITLE
example run fail

### ISSUE THREAD

**Issue by muziling** [OndrejKunc/flutter_dynamic_forms#53]
assets xml or json file has slider, but when run , error log:
E/flutter (11857): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: No parser for element name slider found
E/flutter (11857): #0      FormParserService.parseElement (package:dynamic_forms/src/parser/form_parser_service.dart:28:7)
E/flutter (11857): #1      JsonParserNode.getChildren.<anonymous closure> (package:dynamic_forms/src/parser/json/json_parser_node.dart:51:31)
E/flutter (11857): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
E/flutter (11857): #3      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
E/flutter (11857): #4      CastIterator.moveNext (dart:_internal/cast.dart:63:30)
E/flutter (11857): #5      new List.from (dart:core-patch/array_patch.dart:35:29)
E/flutter (11857): #6      Iterable.toList (dart:core/iterable.dart:400:5)
E/flutter (11857): #7      JsonParserNode.getChildren (package:dynamic_forms/src/parser/json/json_parser_node.dart:53:14)
E/flutter (11857): #8      FormGroupParser.parse (package:flutter_dynamic_forms_components/src/components/form_group/form_group_parser.g.dart:18:28)
E/flutter (11857): #9      FormParserService.parseElement (package:dynamic_forms/src/parser/form_parser_service.dart:30:19)
E/flutter (11857): #10     JsonParserNode.getChildren.<anonymous closure> (package:dynamic_forms/src/parser/json/json_parser_node.dart:51:31)
E/flutter (11857): #11     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
E/flutter (11857): #12     ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
E/flutter (11857): #13     CastIterator.moveNext (dart:_internal/cast.dart:63:30)
E/flutter (11857): #14     new List.from (dart:core-patch/array_patch.dart:35:29)
E/flutter (11857): #15     Iterable.toList (dart:core/iterable.dart:400:5)
E/flutter (11857): #16     JsonParserNode.getChildren (package:dynamic_forms/src/parser/json/json_parser_node.dart:53:14)
E/flutter (11857): #17     FormParser.parse (package:flutter_dynamic_forms_components/src/components/form/form_parser.g.dart:18:28)
E/flutter (11857): #18     FormParserService.parseElement (package:dynamic_forms/src/parser/form_parser_service.dart:30:19)
E/flutter (11857): #19     FormParserService.parse (package:dynamic_forms/src/parser/form_parser_service.dart:19:12)
E/flutter (11857): #20     FormManagerBuilder.build (package:dynamic_forms/src/form_manager/form_manager_builder.dart:15:34)
E/flutter (11857): #21     _SimpleFormScreenState._buildForm (package:example/simple_form/simple_form_screen.dart:52:39)

**Comment by OndrejKunc** [comment]
Hi @muziling,
unfortunately, I am not able to reproduce this issue.
Based on the stack trace it looks like you are running the example project in the flutter_dynamic_forms_components package. It also looks like there is a missing parser object for the slider component. Because the slider component was added recently to the flutter_dynamic_forms_components package I guess the issue might be that you pulled the new changes but you are building your project against the old dependency where there was no slider parser.

Please try calling
`flutter packages upgrade` to refresh dependencies and `flutter clean` before building the project.

Or remove those lines from the pubspec,yaml:   
```yaml
flutter_dynamic_forms_components:
    path: ../
```
save the file, add it back again and save it one more time.

Please let me know if this helps.

Thanks!

**Comment by muziling** [comment]
Seems flutter_dynamic_forms_components  version 0.7.2 not support  slide,  remove slide from json file temporary ,My app no need slide now

**Comment by OndrejKunc** [comment]
Oh, now I see!
I forgot to publish the new version to the pub.

It is published now so you can just update it to 0.7.3.

**Comment by muziling** [comment]
Thanks ,  close.
