### ISSUE TITLE
How to set textInputType

### ISSUE THREAD

**Issue by muziling** [OndrejKunc/flutter_dynamic_forms#56]
Json or xml format , how to set textInputType

**Comment by muziling** [comment]
I look up the source code , now know how to set, close.

**Comment by muziling** [comment]
https://stackoverflow.com/questions/49577781/how-to-create-number-input-field-in-flutter
can i set digitsOnly?
inputFormatters: <TextInputFormatter>[
        WhitelistingTextInputFormatter.digitsOnly
    ],

**Comment by kalismeras61** [comment]
> https://stackoverflow.com/questions/49577781/how-to-create-number-input-field-in-flutter
> can i set digitsOnly?
> inputFormatters: [
> WhitelistingTextInputFormatter.digitsOnly
> ],

You can create your own component.

**Comment by muziling** [comment]
https://stackoverflow.com/questions/45900387/multi-line-textfield-in-flutter
How to set minline and maxline ,   I need to create my own component?

**Comment by kalismeras61** [comment]
> https://stackoverflow.com/questions/45900387/multi-line-textfield-in-flutter
> How to set minline and maxline , I need to create my own component?

Default  Text component doesn't support your requests. You have to create your own component, if you want only change renderer side you can only create your own renderer class.

**Comment by muziling** [comment]
> Default Text component doesn't support your requests. You have to create your own component, if you want only change renderer side you can only create your own renderer class.

I add line 
maxLines: textInputType == TextInputType.multiline ? null : 1,
and works

`  @override
  Widget build(BuildContext context) {
    if (_controller.text != widget.text) {
      _controller.text = widget.text;
    }
    var textInputType = getTextInputType(widget.textInputType);

    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: TextField(
        decoration: InputDecoration(
            labelText: widget.label, errorText: widget.errorText),
        keyboardType: textInputType,
        controller: _controller,
        maxLines: textInputType == TextInputType.multiline ? null : 1,
      ),
    );
  }`

**Comment by OndrejKunc** [comment]
Great! So I am closing this.

Just as @kalismeras61 pointed out, you can always write your custom Renderer object, if you want to only change the appearance of the widget. If you want to also send this value from the server, you would need to write your custom TextField component (Model, Parser, Renderer).

If you have any more questions, feel free to ask.
