### ISSUE TITLE
Running example failed at pub get stage

### ISSUE THREAD

**Issue by siliconxp** [OndrejKunc/flutter_dynamic_forms#84]
There seems to be a version conflict on the dependances.

Below is that out put from `flutter pub get`

Because no versions of flutter_bloc_extensions match >0.1.2 <0.2.0 and flutter_bloc_extensions 0.1.2 depends on flutter_bloc ^0.13.0, flutter_bloc_extensions ^0.1.2 requires flutter_bloc ^0.13.0.
And because no versions of flutter_bloc match >0.13.0 <0.14.0, flutter_bloc_extensions ^0.1.2 requires flutter_bloc 0.13.0.
And because flutter_bloc 0.13.0 depends on bloc ^0.13.0 and no versions of bloc match >0.13.0 <0.14.0, flutter_bloc_extensions ^0.1.2 requires bloc 0.13.0.
And because bloc 0.13.0 depends on rxdart ^0.22.0 and every version of dynamic_forms from git depends on rxdart ^0.23.1, flutter_bloc_extensions ^0.1.2 is incompatible with dynamic_forms from git.
And because every version of flutter_dynamic_forms_components from path depends on flutter_dynamic_forms from git which depends on dynamic_forms from git, flutter_bloc_extensions ^0.1.2 is incompatible with flutter_dynamic_forms_components from path.
So, because example depends on both flutter_dynamic_forms_components from path and flutter_bloc_extensions ^0.1.2, version solving failed.
Running "flutter pub get" in example...
pub get failed (1; So, because example depends on both flutter_dynamic_forms_components from path and flutter_bloc_extensions ^0.1.2, version solving failed.)

**Comment by OndrejKunc** [comment]
Hi, this is very strange.
`flutter_bloc_extensions` dependency was used in very old versions of the project in the examples.
Where exactly are you running `flutter pub get` command? It works on both example projects in this repo for me. If it is in your project, what dependencies are you using?

**Comment by siliconxp** [comment]
I recloned the repo. Working perfectly. Thank you for your great work.
