### ISSUE TITLE
The exclamation mark for equality operator (!=) is clashing with unary negate operator or postfix operator (!)

### ISSUE THREAD

**Issue by raphire08** [OndrejKunc/flutter_dynamic_forms#99]
I just ran a simple example "3 != 2", I got error for this. On changing the token for  the unary negate operator and postfix operator  to "!!" from "!", it worked.

**Comment by OndrejKunc** [comment]
Hi, thanks for reporting this issue. 
I have totally missed this case and unfortunately, there was no test for it. I fixed it and published the new version of `expression_language` package (1.0.1) to the pub.dev.

**Comment by raphire08** [comment]
Thanks for writing such a beautiful library. I am a beginner programmer,
but I must say that I got very much inspired by it and hope to code this
impressively in future. Thanks
